//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vino
    {
        public int Id { get; set; }
        public string ImagenUri { get; set; }
        public int IdTipoVino { get; set; }
        public int IdMarca { get; set; }
        public int IdCepa { get; set; }
        public string Pais { get; set; }
        public System.DateTime Cosecha { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public int Stock { get; set; }
    
        public virtual Cepa Cepa { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual TipoVino TipoVino { get; set; }
    }
}
